# Streamlit secrets configuration template
# Copy this to your app's .streamlit/secrets.toml and customize as needed

[general]
hostname = "impact-model on Streamlit Server"
environment = "production"
version = "1.0.0"
app_name = "impact-model"

[server]
name = "streamlit-hosting-platform"
location = "/mnt/storage"
docker_network = "streamlit-network"

# Database configuration (example)
# [database]
# username = "your_db_user"
# password = "your_db_password"
# host = "localhost"
# port = 5432

# API keys (example)
# [api_keys]
# openai_api_key = "your_api_key_here"
# google_api_key = "your_google_key_here"

# Custom app settings (example)
# [app_settings]
# max_upload_size = "200MB"
# cache_ttl = 3600
# debug_mode = false
