# Streamlit secrets configuration
# This file contains configuration and secret values for the Streamlit app

[general]
hostname = "Streamlit Server"
environment = "production"
version = "1.0.0"

[server]
name = "streamlit-hosting-platform"
location = "/mnt/storage"
docker_network = "streamlit-network"

# Add your own secrets here as needed
# [database]
# username = "your_db_user"
# password = "your_db_password"
# host = "localhost"
# port = 5432

# [api_keys]
# openai_api_key = "your_api_key_here"
# google_api_key = "your_google_key_here"
